### ISSUE TITLE
Missing cplusplus directive in sim_imp.h?

### ISSUE THREAD

**Issue by rudolfochrist** [larsbrinkhoff/imp#2]
Hi, 

I was just skimming the code and I'm actually not a C programmer, so it is very likely that I'm wrong, but isn't the `__cplusplus`  closing directive missing in sim_imp.h?

I mean, it is present in `sim_ncp.h`:
https://github.com/larsbrinkhoff/imp/blob/08fc822799b6e6a898990cdcb046b1f34ef807c2/src/sim_ncp.h#L21-L23

Could it have been forgotten or is it just uneccessary? I'm curious :smile: 

Thanks.

-Sebastian

**Comment by larsbrinkhoff** [comment]
Yes, it is.  Thanks!

**Comment by larsbrinkhoff** [comment]
Fixed.  I think.  This code doesn't build by itself yet.
